name: realkinova_xhand
task_type: single_dataset
task_modes: []

shape_meta:
  image_resolution: 96
  action:
    shape:
    - 38
  obs:
    state:
      shape:
      - 38
      type: low_dim
    image:
      shape:
      - 3
      - 96
      - 96
      type: rgb
    image_right:
      shape:
      - 3
      - 256
      - 256
      type: rgb
    ee_left:
      shape:
      - 6
      type: low_dim
    ee_right:
      shape:
      - 6
      type: low_dim
    q_left:
      shape:
      - 19
      type: low_dim
    q_right:
      shape:
      - 19
      type: low_dim

dataset:
  _target_: unified_video_action.dataset.teleop_dataset.RealKinovaXHandDataset
  language_emb_model: null
  horizon: 32
  pad_after: 7
  pad_before: 1
  seed: 42
  val_ratio: 0.02
  normalizer_type: all
  dataset_path: data/realkinova_xhand/demo.zarr
  dataset_type: singletask
  image_right_resolution: 256

env_runner:
  _target_: unified_video_action.env_runner.teleop_image_runner.TeleopImageRunner
  arm_hand_name: realkinova_xhand
  dataset_path: data/realkinova_xhand/demo.zarr
  fps: 10
  max_steps: 227
  n_action_steps: 8
  n_envs: null
  n_obs_steps: 16
  n_test: 1
  n_test_vis: 1
  n_train: 1
  n_train_vis: 1
  past_action: false
  test_start_seed: 100000
  train_start_seed: 0
